### ISSUE TITLE
User Story: Poll deadlines

### ISSUE THREAD

**Issue by HughKeenan** [HughKeenan/First-agile-project#6]
As an **administrator** I can **set time limits** so that **polls can be concluded at the appropriate time**

## Acceptance Criteria

- Criteria 1: Display expiration date for poll
- Criteria 2: Provide updates on how long is left
- Criteria 3: Remove poll once deadline reached

## Tasks

- [ ] Task 1: Write code to provide deadline date in DD/MM/YYYY format above poll
- [ ] Task 2: Write code to display how long left in days before deadline
- [ ] Task 3: Write code to prevent submissions after deadline
